const menu = [
  {
    id: 1,
    title: 'MENEMEN',
    category: 'Yiyecek',
    price: 60.00,
    img: '/images/menemen.dng',
    desc: `İçerik :Biber, Domates, (istege göre sogan) Yumurta .`,
  },
  {
    id: 2,
    title: 'OMLET',
    category: 'Yiyecek',
    price: 40.00,
    img: '/images/omlet.dng',
    desc: `İçerik Teretagı eşiginde yumurta tavada sevris edilir.`,
  },
  {
    id: 3,
    title: 'KAHVALTI TABAĞI',
    category: 'Yiyecek',
    price: 65.00,
    img: '/images/kahvaltı.jpeg',
    desc: `İçerik :Haşlanmış yumurta(istege göre omlet) Peynir, Domates, Salatalık, Zeytin, Reçel,Patates .`,
  },
  {
    id: 4,
    title: 'KAVURMALI YUMURTA',
    category: 'Yiyecek',
    price: 75.00,
    img: '/images/kyumurta.jpg',
    desc: `İçerik Kavurtma eti teragıyı eşliginde 2 yumurta ile tavada sevris edilir.`,
  },

  {
    id: 5,
    title: 'KARIŞIK TOST',
    category: 'Yiyecek',
    price: 50.00,
    img: '/images/kktost.jpg',
    desc: `İçerik :Tost Ekmeği arası sucuk ve kaşar peyniri. Patates kızartması eşliğinde.`,
  }, 
  {
    id: 6,
    title: 'GÖZLEME',
    category: 'Yiyecek',
    price: 50,
    img: '/images/kumrugözleme.jpg',
    desc: `İçerik: Kumru gözleme (Sosis , Salam , Sucuk , Kaşar peyniri). isteğe göre sade kaşarlı ve çiştlerimiz mevcuttur.  .`,
  }, 
  {
    id: 7,
    title: 'KAŞARLI TOST',
    category: 'Yiyecek',
    price: 40.00,
    img: '/images/ktost.jpg',
    desc: `İçerik :Tost Ekmeği arası kaşar peyniri.ve patates kızartması eşliğinde.`,
  }, 
  {
    id: 8,
    title: 'KAVURMALI KAŞARLI TOST',
    category: 'Yiyecek',
    price: 70.00,
    img: '/images/kavurma.jpg',
    desc: `İçerik :Tost ekmeği arası kaşar peyniri ve kavurma ve patates kızartması eşliğinde.`,
  },
  {
    id: 9,
    title: 'SUCUKLU TOST',
    category: 'Yiyecek',
    price: 42.00,
    img: '/images/stost.jpg',
    desc: `İçerik :Tost ekmeği arası sucuk. ve patates kızartması eşliğinde.`,
  },
  {
    id: 10,
    title: 'PATSO',
    category: 'Yiyecek',
    price: 35.00,
    img: '/images/patsoo.png',
    desc: `İçerik: Patso ekmegine patso baharatlı patates istege göre ketçap mayonez .`,
  },
  {
    id: 11,
    title: 'SUCUKLU PATSO',
    category: 'Yiyecek',
    price: 37.00,
    img: '/images/spatso.png',
    desc: `İçerik: Patso ekmegine patso baharatlı patates ve sucuk istege göre ketçap mayonez .`,
  },
  {
    id: 12,
    title: 'SUCUKLU KAŞARLI PATSO',
    category: 'Yiyecek',
    price: 40.00,
    img: '/images/skpatso.png',
    desc: `İçerik: Patso ekmegine patso baharatlı patates, sucuk ve kaşar istege göre ketçap mayonez .`,
  },
  {
    id: 13,
    title: 'KAŞARLI PATSO',
    category: 'Yiyecek',
    price: 37.00,
    img: '/images/kpatso.png',
    desc: `İçerik: Patso ekmegine patso baharatlı patates ve kaşar istege göre ketçap mayonez .`,
  }
  ,
  {
    id: 14,
    title: 'SOSİSLİ KAŞARLI PATSO',
    category: 'Yiyecek',
    price: 40.00,
    img: '/images/kpatso.png',
    desc: `İçerik: Patso ekmegine patso baharatlı patates, sosis ve kaşar istege göre ketçap mayonez .`,
  },
  {
    id: 15,
    title: 'KARIŞIK PATSO',
    category: 'Yiyecek',
    price: 45.00,
    img: '/images/kkkpatso.png',
    desc: `İçerik: Patso ekmegine patso baharatlı patates sucuk, sosis ve kaşar istege göre ketçap mayonez .`,
  },
  {
    id: 16,
    title: 'SOSİSLİ',
    category: 'Yiyecek',
    price: 32.00,
    img: '/images/sosisli.png',
    desc: `İçerik: Patso ekmegine sosis sos istege göre ketçap mayonez .`,
  },
  {
    id: 17,
    title: 'SOĞUK SANDVİÇ',
    category: 'Yiyecek',
    price: 30.00,
    img: '/images/sandavic.png',
    desc: `İçerik: Patso ekmegine Salam, Beyaz Peynir, Kaşar,Domates, Salatalık, Marul.`,
  },
  
  {
    id: 18,
    title: 'PACANGA',
    category: 'Yiyecek',
    price: 10.00,
    img: '/images/pacanga.dng',
    desc: `İçerik:  Kaşar, Salam, Sosis, Kapya biber, (adet fiyatıdır.)`,
  },
  {
    id: 19,
    title: 'SİĞARA BÖREĞİ',
    category: 'Yiyecek',
    price: 7.00,
    img: '/images/sigarab.jpeg',
    desc: `İçerik:   yufka ekmeği içerisinde peynir , maydanoz (adet fiyatıdır.) `,
  },
  {
    id: 20,
    title: 'LİMONATA',
    category: 'İçecek',
    price: 25,
    img: '/images/limonata.jpg',
    desc: `Ev yapımı limonatamıza diyecek bişey yok tavsiye ederiz.`,
  },
  {
    id: 21,
    title: 'SOĞUK KAHVE',
    category: 'İçecek',
    price: 25,
    img: '/images/skahve.jpg',
    desc: `Özel demlenmiş kahve istege göre sade ve sütlü şeklinde sevris edilir.`,
  },
  {
    id: 22,
    title: 'COOL LİME',
    category: 'İçecek',
    price: 25,
    img: '/images/cool.jpg',
    desc: `Yaz aylarında sıcak havadan bunalıp ferahlamak isteyenlerin tercihi.`,
  },
  {
    id: 23,
    title: 'CHURCHİLL',
    category: 'İçecek',
    price: 25,
    img: '/images/chur.jpg',
    desc: `Churchill soda, tuz ve limon suyunun buluşmasıyla hazırlanan, lezzetli soğuk bir içecektir.`,
  },
  
  {
    id: 24,
    title: 'MADEN SUYU',
    category: 'İçecek',
    price: 7,
    img: '/images/akmina.jpg',
    desc: `beypazrı, damla ve akmina - Limon, Ananas, Elma, Nar, Kırmızı Orman Meyveleri Çeşitlerimiz mevcuttur.`,
  },
  {
    id: 25,
    title: 'CİPS',
    category: 'Atıştırmalık',
    price: 20,
    img: '/images/cipsss.jpg',
    desc: `Lays, Doritos(cubun), Ruffles, Çerezza çeşitleri mevcuttur.`,
  },
  {
    id: 26,
    title: 'MAGNUM',
    category: 'Dondurma',
    price: 25,
    img: '/images/magnum.jpg',
    desc: `Algida Magnum Classic ,Badem ,Düet Kırmızı Meyveler,Magnum Double Karadut & Böğürtlen,Magnum Cookie , Magnum Double Starchaser  çeşitler mevcuttur `,
  },
  
  {
    id: 27,
    title: 'Kahve ve çay',
    category: 'Çay Kahve',
    price: 0,
    img: '/images/kahve.jpg',
    desc: `İçerik: Ada çayları çeşitleri , Babil ve Dibek kahve çeşitleri menengiç , dibek , antep fıstıklı dibek ve osmanlı dibek kahvesi çeşitleri   `,
  },
  {
    id: 28,
    title: 'Kahve Çeşitleri',
    category: 'Çay Kahve',
    price: 0,
    img: '/images/kahveçay.jpg',
    desc: `İçerik: Elruha 400 gr ve 800 gr çay çeşitleri , 3 ü 1 arada kahve çeiştleri mevcuttur.   `,
  },
  {
    id: 29,
    title: 'ANKARA MAKARNA',
    category: 'Gıda',
    price: 15.00,
    img: '/images/ankara makarna.jpg',
    desc: `Spaghetti, Fiyonk, Burgu, Yüksük, Kelebek çeşitlerimiz mevcuttur.`,
  },
  {
    id: 30,
    title: 'KURUYEMİŞ',
    category: 'Çerez',
    price: 0,
    img: '/images/kuruyemiş.jpeg',
    desc: `çeşitlerimiz mevcuttur whatsapp dan sipariş verebilirsiniz.`,
  },

  {
    id: 31,
    title: 'Elektronik',
    category: 'Elektronik',
    price: 0,
    img: '/images/elektronik.jpg',
    desc: `Şarj başlıkları , şarj kabloları (type-c ve iphone), powerbank ,kulaklık , aux kablosu , Araç çakmaklığı , Araç çakmaklık mp3, Telefon tucu , Duracell saat ve kalem pil  `,
  },
  {
    id: 32,
    title: 'Kırtasiye',
    category: 'Kırtasiye',
    price: 0,
    img: '/images/kırtasiye.jpg',
    desc: `A3,A4,A5, Diplomat , Mektup Zarfı, japon yapıştırıcı , dosya çeşitleri, zımba , delgeç ,senet, not defteri, ve Kalem  Çeşitlerimiz mevcuttur.`,
  },
  {
    id: 33,
    title: 'OFİS TEMİZLİK ÜRÜNLERİ',
    category: 'Temizlik',
    price: 0,
    img: '/images/temizlik.jpg',
    desc: `Çamaşır suyu,Bulaşık deterjanı,Sıvı sabun Yag,kireç sökücü, Oda kokusu, Camsil Sarı bez, Cam bezi Bulaşık süngeri Küçük büyük battal boy çöp torbası karton pet baradak Yüzey temizleyici çeşitlerimiz vardır.
     fiyat bilgisi için whapsapdan yazabilirsiniz.`,
  },

  {
    id: 34,
    title: 'KOKUSUZ KÜLLÜK',
    category: 'Oto Aksesuar',
    price: 15,
    img: '/images/küllük.jpg',
    desc: `Araç içi veya ofis için kokusuz küllük`,
  },
  { 
    id: 35,
    title: 'KOLA',
    category: 'İçecek',
    price: 15,
    img: '/images/gazlı.jpg',
    desc: `Cocacola,Fanta,Pepsi, Sprite ,Schweppes  şişe , kutu, 1 litre, 1.5 litre, 2,5 litre çeşitlerimiz mevcuttur. ,`,
  },
  {
    id: 36,
    title: 'CORNETTO',
    category: 'Dondurma',
    price: 25,
    img: '/images/dondurma cornetto.jpg',
    desc: `Cornetto classic ,Aşk ateşi çeşitleri mevcuttur `,
  },
  {
    id: 37,
    title: 'CLASSİCS',
    category: 'Dondurma',
    price: 10,
    img: '/images/nogger.jpg',
    desc: `Classics , Keyif, Nogger, Frigola , Toblerone , Combo çeşitlerimiz mevcuttur `,
  },
  
  {
    id: 38,
    title: 'İNDOMİE NOODLE',
    category: 'Gıda',
    price: 6.5,
    img: '/images/nodle.jpg',
    desc: `Tavuk, Sebze, Kori, Spesiyal Aromalı çeşitlerimiz mevcuttur.`,
  },
  
  {
    id: 39,
    title: 'SIVI YAĞ',
    category: 'Gıda',
    price: 45,
    img: '/images/yag.jpg',
    desc: `Besler 1 lt Ayçiçek yağı`,
  },
  
  {
    id: 40,
    title: 'Baharat',
    category: 'Gıda',
    price: 0,
    img: '/images/baharat.jpg',
    desc: `Tüm baharat çeşiteri ve Salina sofra tuzu 500 gr tuzluk ambalajı ve 750 gr poşet ambalajlı çeşitleri mevcuttur.`,
  },
  { 
    id: 41,
    title: 'GAZOZ',
    category: 'İçecek',
    price: 10,
    img: '/images/gazozz.jpg',
    desc: `Beyoğlu sade, Beyoglu Turunçgiller, Çamlıca, Çamlıca Portakal, Nigde , Beylerbeyi gazoz cam şişe  çeşitlerimiz mevcuttur. ,`,
  },
  {
    id: 42,
    title: 'ATIŞTIRMALIK',
    category: 'Atıştırmalık',
    price: 9.99,
    img: '/images/atıştırmalık.jpg',
    desc: `Tüm Eti,Ülker çikolata bisküvi  çeşitleri mevcuttur.`,
  },
  {
    id: 43,
    title: 'SAKIZ',
    category: 'Atıştırmalık',
    price: 9.99,
    img: '/images/sakız.jpg',
    desc: `Falım, Vivident , Oneo , Yıldız sakız   çeşitleri mevcuttur.`,
  },  
  {
    id: 44,
   title: 'SİGARA',
   category: 'Sigara',
   price: 43,
   img: '/images/ekrem.jpg',
   desc: `tüm sigara çeşitleri 41.00 tl -47.00 tl `,
 },

]; 
export default menu;
