const menu = [
  {
    id: 1,
    title: 'Eti Tutku',
    category: 'Atıştırmalık',
    price: 8.99,
    img: '/images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
  },
  {
    id: 2,
    title: 'Hamburger',
    category: 'Yiyecek',
    price: 13.99,
    img: '/images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing.`,
  },
  {
    id: 3,
    title: 'Fanta',
    category: 'İçecek',
    price: 5.99,
    img: '/images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'Marlboro',
    category: 'Sigara',
    price: 29.99,
    img: '/images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Algida',
    category: 'Dondurma',
    price: 7.99,
    img: '/images/item-5.jpeg',
    desc: `Antep fıstıklı, çikolatalı, vanilyalı çeşitler mevcuttur `,
  },
  {
    id: 6,
    title: 'Filiz Makarna',
    category: 'Gıda',
    price: 9.99,
    img: '/images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 11,
    title: 'Fıstık',
    category: 'Çerez',
    price: 21.99,
    img: '/images/item-11.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },

  {
    id: 8,
    title: 'JBL Kulaklık',
    category: 'Elektronik',
    price: 89.99,
    img: '/images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Not Defteri',
    category: 'Kırtasiye',
    price: 12.99,
    img: '/images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'Deterjan',
    category: 'Temizlik',
    price: 16.99,
    img: '/images/item-10.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 7,
    title: 'Vavana Araç Kokusu',
    category: 'Oto Aksesuar',
    price: 45.99,
    img: '/images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },

];
export default menu;
